apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2024-06-07T16:46:50Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "14380"
  uid: 9b454b6e-a9ee-4076-9c2d-6cbea55178e4
data:
  repositories: |
    - url: https://github.com/apipinic/document-cloud-app-deployment
      usernameSecret:
        name: my-git-secret
        key: username
      passwordSecret:
        name: my-git-secret
        key: password