replicaCount: 2
image:
  repository: ghcr.io/apipinic
  tag: latest
awsRegion: eu-central-1
dynamoDbTableName: documents-cloud-table-schuetz-1
s3BucketName: documents-cloud-bucket-schuetz-1
roleArn: arn:aws:iam::252259669656:role/EKS-DynamoDB-S3-Role
secretKey: ""
dockerconfigjson: ""
createDockerConfigSecret: true
service:
  loginService:
    name: login-service
    port: 80
  documentViewerService:
    name: document-viewer
    port: 8081
  documentShareService:
    name: document-share
    port: 8082
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  hosts:
    - host: chart-example.local
      paths:
        - path: /documents
          pathType: Prefix
          backend:
            service:
              name: document-viewer
              port:
                number: 8081
        - path: /health-login
          pathType: Prefix
          backend:
            service:
              name: login-service
              port:
                number: 80
        - path: /health-document
          pathType: Prefix
          backend:
            service:
              name: document-viewer
              port:
                number: 8081
        - path: /share
          pathType: Prefix
          backend:
            service:
              name: document-share
              port:
                number: 8082
        - path: /health-share
          pathType: Prefix
          backend:
            service:
              name: document-share
              port:
                number: 8082
        - path: /
          pathType: Prefix
          backend:
            service:
              name: login-service
              port:
                number: 80
  tls: []
