apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.documentShareService.name }}
spec:
  selector:
    app: document-share
  ports:
    - protocol: TCP
      port: {{ .Values.service.documentViewerService.port }}
      targetPort: 8082