apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.documentViewerService.name }}
spec:
  selector:
    app: document-viewer
  ports:
    - protocol: TCP
      port: {{ .Values.service.documentViewerService.port }}
      targetPort: 8081