apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: {{ .Values.image.repository }}/login-service:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: SECRET_KEY
      imagePullSecrets:
      - name: dockerconfigjson-github-com
