apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.loginService.name }}
spec:
  selector:
    app: login-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.loginService.port }}
      targetPort: 5000