apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey }}